theme: jekyll-theme-cayman
title: OpenHRS
description: Search for laws. Discover your rights.
show_downloads: false

gems:
  - jekyll-mentions

jekyll-mentions:
  base_url: https://github.com/OpenHRS
